#!/usr/bin/env sh

# The scripting addition must be loaded manually if you are
# running yabai on MacOS BigSur.
# Uncomment the following line to have the injection performed
# when the config is executed during startup.
# NOTE: You might need to configure sudo to work without asking for a password.
# More info in: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load sa"

# Global settings
yabai -m config mouse_follows_focus    off
yabai -m config focus_follows_mouse    off
yabai -m config window_origin_display  default
yabai -m config window_placement       second_child
yabai -m config window_topmost         on
yabai -m config window_shadow          off
yabai -m config window_opacity         on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity  1.0
yabai -m config normal_window_opacity  0.9
yabai -m config window_border          on
yabai -m config window_border_width    1
yabai -m config insert_feedback_color  0xffd75f5f
yabai -m config normal_window_border_color 0xffA282C3
yabai -m config active_window_border_color 0xffE06C75
# Colors:
#   GREY: ABB2BF; BLUE: 61AFEF; RED: E06C75; PURPLE: C678DD; DARK: 282C34
yabai -m config split_ratio           0.50
yabai -m config auto_balance          off
yabai -m config mouse_modifier        fn
yabai -m config mouse_action1         move
yabai -m config mouse_action2         resize
yabai -m config mouse_drop_action     swap
yabai -m config layout                bsp
yabai -m config top_padding           0
yabai -m config bottom_padding        0
yabai -m config left_padding          0
yabai -m config right_padding         0
yabai -m config window_gap            5

# Application specific rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
